### ISSUE TITLE
Semantic Release does not fetch most recent releases from GitHub

### ISSUE THREAD

**Issue by timoknapp** [go-semantic-release/semantic-release#105] opened 2021-01-28 18:32 UTC
Hi @christophwitzko ,

I just stumpled upon a pretty weird behaviour regarding the way `semantic-release` fetches the releases of the relevant repository. While using `semantic-release` with GitLab in production for quite a while now, I just noticed that in GitHub it wont fetch the latest tags (Releases) and therefore wont generate the new `semantic-version` correctly.

Here is a sample repo of mine:

[List of tags](https://github.com/timoknapp/sound-on-fire/tags)

![image](https://user-images.githubusercontent.com/11437666/106181278-b044f100-619d-11eb-9ce6-fcf50619e9eb.png)

When running the action afterwards it does not fetch the latest tag being `1.3.0` and therefore still shows the version `1.2.4`. (You can ignore my custom made build numbers `+XXX`) Also don't bother the execution in `dry` - mode, its only used for extracting the `semantic-version` and combine it with the build number.  

[Semantic Release in GitHub Action](https://github.com/timoknapp/sound-on-fire/runs/1764830585?check_suite_focus=true#step:4:21)

![image](https://user-images.githubusercontent.com/11437666/106181651-26495800-619e-11eb-81a5-c30c6e1c6297.png)

I also ran `semantic-release` locally to be sure that its the same behaviour and unfortunately it is consistent:

![image](https://user-images.githubusercontent.com/11437666/106182251-dc14a680-619e-11eb-87ee-af18ea96c2f0.png)

Do you know where this could be coming from? 

Thanks in advance!
Timo

**Comment by timoknapp** [comment] 2021-01-28 19:43
Hi @christophwitzko ,

Understood. Are you already working on a fix for this or is there already a PR upcoming?

**Comment by christophwitzko** [comment] 2021-01-30 20:01
Hi @timoknapp,

I looked more into your issue and was not able to reproduce it:
```
[go-semantic-release]: version: 2.13.0
[go-semantic-release]: ci-condition plugin: default@1.2.2
[go-semantic-release]: provider plugin: GitHub@1.4.1
[go-semantic-release]: getting default branch...
[go-semantic-release]: found default branch: master
[go-semantic-release]: found current branch: master
[go-semantic-release]: found current sha: master
[go-semantic-release]: getting latest release...
[go-semantic-release]: found version: 1.3.1+121
[go-semantic-release]: getting commits...
[go-semantic-release]: analyzing commits...
[go-semantic-release]: commit-analyzer plugin: default@1.3.1
[go-semantic-release]: calculating new version...
[go-semantic-release]: no change
```
Your tags seem also not annotated, so the provider works fine. Do you still see the error?

**Comment by timoknapp** [comment] 2021-01-30 20:13
Hi @christophwitzko ,

haha I already changed the Tags from annotated to lightweight ones 😂

In case you want retry, simple create some tags like the following: `git tag -fa $TAGNAME`

Here is how I created them beforehand:

https://github.com/timoknapp/sound-on-fire/commit/b232a7202798fe0afdef43f10a81b2221bd4f212

Thanks for your support!
Timo

**Comment by christophwitzko** [comment] 2021-01-30 20:15
Ahhh, okay. 😅 Great, I will work on a fix to support annotated tags. 👍

**Comment by christophwitzko** [comment] 2021-01-30 20:42
I will close this issue in favor of https://github.com/go-semantic-release/provider-github/issues/3

**Closed by christophwitzko** 2021-01-30 20:42 UTC

**Comment by christophwitzko** [comment] 2021-01-30 21:00
@timoknapp The fix is now merged, annotated tags should work now ☺️

**Comment by timoknapp** [comment] 2021-01-30 21:04
@christophwitzko 

Awesome thanks for the hotfix 👍
