### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by dfang** [go-semantic-release/semantic-release#159] opened 2023-09-04 04:21 UTC
what is default CI Condition ? how is it different from CI Condition: Github ?

and how to install it by using `go install` ?

`go install github.com/go-semantic-release/semantic-release@v2.27.1` fails on go 1.21.0

**Comment by christophwitzko** [comment] 2023-09-11 12:45
Hey @dfang,

sorry about the incomplete docs 😢

You can install the tool either via npm or curl: https://github.com/go-semantic-release/semantic-release#installation

> what is default CI Condition ?

The default CI condition is a fallback plugin if the CI cannot be detected and does not check anything: https://github.com/go-semantic-release/condition-default/blob/master/pkg/condition/default.go


> how is it different from CI Condition: Github ?

The GitHub Actions condition checks if `go-semantic-release` should create a new release or not (e.g. if it is running on the default branch): https://github.com/go-semantic-release/condition-github/blob/master/pkg/condition/github.go

Closing this as a duplicate of #146 

Best,
Chris

**Closed by christophwitzko** 2023-09-11 12:45 UTC
